In [6]:
class Point :
    x = 0
    y = 0
    def __init__(self,a,b):
        self.x=a
        self.y=b
    def __add__(self,other):
        self.x = self.x+other.x
        self.y = self.y+other.y
        return self
    def show(self):
        print("(",self.x,",",self.y,")")
    
a = Point(1,2)
a.show()

b= Point(3,4)
b.show()

a= a+b
a.show()

( 1 , 2 )
( 3 , 4 )
( 4 , 6 )


In [7]:
import csv
f= open('seoul.csv','r',encoding='cp949')
data = csv.reader(f)
header = next(data)
day = 0
dif = [0]
for row in data:
    day += 1
    if day==8:
        day=1
        dif.append(float(row[-1])-float(row[-2]))
    else:
        dif[-1]= dif[-1]+(float(row[-1])-float(row[-2]))
max = -1
for i in dif:
    if max<i:
        max=i
tmp = dif.index(max)
if tmp == 0 :
    print("Max week = 5/1 ~ 5/7")
elif tmp == 1:
    print("Max week = 5/8 ~ 5/14")
elif tmp == 2:
    print("Max week = 5/15 ~ 5/21")
elif tmp == 3:
    print("Max week = 5/22 ~ 5/28")
elif tmp == 4:
    print("Max week = 5/29 ~ 5/31")



Max week = 5/8 ~ 5/14


In [26]:
import numpy as np
import matplotlib.pyplot as plt

docs = np.array([1,1,0,1,0,1,1,1,1,0,1,0,1,1,0,1,0,0]).reshape(3,6)

query = np.array([1,1,0,0,1,0])
a= docs*query
l = []


abs(docs)*abs(docs)
#각 엘리먼트 곱해서 다 더해

[1 1 0 0 1 0]
[1 1 0 0 1 0]
[1 1 0 0 1 0]
[1 1 0 0 1 0]
[1 1 0 0 1 0]
[1 1 0 0 1 0]
[1 1 0 0 1 0]
[1 1 0 0 1 0]
[1 1 0 0 1 0]
[1 1 0 0 1 0]
[1 1 0 0 1 0]
[1 1 0 0 1 0]
[1 1 0 0 1 0]
[1 1 0 0 1 0]
[1 1 0 0 1 0]
[1 1 0 0 1 0]
[1 1 0 0 1 0]
[1 1 0 0 1 0]
[0, 0, 0]


array([[1, 1, 0, 1, 0, 1],
       [1, 1, 1, 0, 1, 0],
       [1, 1, 0, 1, 0, 0]])